### PR TITLE
Exceptions

### LINKED ISSUE #17: Practice on catching exceptions
## Description

In this task, we need to practice catching and handling exceptions in our program for the next cases:

1. When the file is not found (`FileNotFoundException`)
   - rename the input file's name so it will refer to a non-existent file;
   - launch the app;
   - catch the `FileNotFoundException` and log it on `ERROR` level;
   - return the empty list of lines from the method;
  
2. When data is in the unexpected format:
     - go to the `books.txt` file;
     - add the line `Franklin,Herbert,1965,Dune` to the end of file;
     - launch the app;
     - catch the exception and log it on `WARNING` level;
     - ignore this line as a result of the parsing method

## Links to read
- 7.1 Dealing with Errors (only 7.1.1 & 7.1.2);
- 7.2 Catching exceptions (7.2.1-4)

---

### PR DESCRIPTION
**Pull request by Geirby**
Handling of "umberFormatException" and "NullPointerException" exceptions

### CODE REVIEW

File: src/main/java/com/company/library/CollectionTask.java [hunk 1]
```diff
@@ -32,69 +39,119 @@ public static void main(String[] args) throws IOException, URISyntaxException {
...
+                    Path.of(
+                            CollectionTask.class
+                                    .getClassLoader()
+                                    .getResource(filepath)
+                                    .toURI()
+                    )
+            )
+                    .toList();
+        } catch (NullPointerException e) {
+            List<String> emptyFile = new ArrayList<>();
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/com/company/library/CollectionTask.java]: Misleading variable name: this is not a file, this is a collection of strings.
More accurate names can be `emptyLines`, `lines`

File: src/main/java/com/company/library/CollectionTask.java [hunk 2]
```diff
@@ -32,69 +39,119 @@ public static void main(String[] args) throws IOException, URISyntaxException {
...
+            System.err.println("File doesn't found");
+            return emptyFile;
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/com/company/library/CollectionTask.java]: You can use the static method `emptyList()` instead of instantiating a new variable;

File: src/main/java/com/company/library/CollectionTask.java [hunk 3]
```diff
@@ -32,69 +39,119 @@ public static void main(String[] args) throws IOException, URISyntaxException {
...
+                            CollectionTask.class
+                                    .getClassLoader()
+                                    .getResource(filepath)
+                                    .toURI()
+                    )
+            )
+                    .toList();
+        } catch (NullPointerException e) {
+            List<String> emptyFile = new ArrayList<>();
+            System.err.println("File doesn't found");
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/com/company/library/CollectionTask.java]: Good! 👍 
It would be nice to mention in the log what file is not found

File: src/main/java/com/company/library/CollectionTask.java [hunk 4]
```diff
@@ -32,69 +39,119 @@ public static void main(String[] args) throws IOException, URISyntaxException {
...
+                bookList.add(new Book(new Author(columns[0], columns[1]), columns[2], Integer.parseInt(columns[3])));
+            }
+            return bookList;
+        } catch (NumberFormatException y) {
+
+            //Pattern exampleString = Pattern.compile(("[a-zA-Z],[a-zA-Z],[a-zA-Z],\\d{4}"), Pattern.CASE_INSENSITIVE);
+
+            System.err.println("Wrong data format at document");
+
         }
```
Comment (Dauren-Delmukhambetov) [inline src/main/java/com/company/library/CollectionTask.java]: This looks good to me! At least. it doesn't stop the app which is great.
However, this one works fine only for the case when invalid lines are at the end of the file.
What if they are in the middle? Or rotates with valid ones?

**Review by Dauren-Delmukhambetov — APPROVED** [review]
